### ISSUE TITLE
Profit is still not done 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#104]
### Profit chart still not done.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/profit-is-still-not-done) 
> ### [Contact the user via email](mailto://danielsmith@juicedio.com) 

*Issue created by [**Daniel Smith**](https://juiced.canny.io/admin/user/daniel-smith-304)  at 2021-12-06T12:45:06.266Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/profit-is-still-not-done) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
Waiting for amazon api bug to be resolved.

**Comment by ssnxd** [comment]
Update: Currently selecting all in filters does not show profit because of amazon API issue therefore it was hidden from all
will update this to showing the profit and with a note if amazon is connected that profit is not accounted.

**Comment by ssnxd** [comment]
@iamsr what charts data currently works for amazon
[ ] Profit
[ ] Sold
[ ] Unsold
[ ] Revenue

and for profit data I get 

```js
[
 {
   createdAt: "2021-12-10T17:30:06.241Z"
   created_at: "2021-10-13"
   currency: "USD"
   id: 2860260
   marketplace_id: null
   percent: 0
   platform: "ebay"
   total_earned: 0
   total_paid: 0
 },
]
```
how to calculate profit is it `total_earned - total_paid` or what? explain this
