### ISSUE TITLE
ebay orders not syncing 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#12]
### ebay shows 0 orders

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/ebay-orders-not-syncing) 
> ### [Contact the user via email](mailto://aekblade@gmail.com) 

*Issue created by [**aekblade**](https://juiced.canny.io/admin/user/aekblade)  at 2021-11-28T20:48:19.888Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/ebay-orders-not-syncing) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
need more information about recreating bug.
