### ISSUE TITLE
Balance Values 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#130]
### When selecting "All Accounts" in the filter options, the balance shows 2 values.
https://screenshot.click/07-44-92906-48781.png
If we only select a single sales channel then the value corrects itself
https://screenshot.click/07-45-88267-18867.png

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/balance-values) 
> ### [Contact the user via email](mailto://brandongurutest@gmail.com) 

*Issue created by [**brandongurutest**](https://juiced.canny.io/admin/user/brandongurutest)  at 2021-12-07T19:03:58.522Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/balance-values) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
@iamsr  Status on this issue?
