### ISSUE TITLE
Notification reminder 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#131]
### The pulsating notif light on the left seems to be inbetween two tabs constantly, also noticed that it appeared almost in the middle of the "Revenue" square when i switched from another tab. (I was unable to recreate it tho )
https://canny.io/images/5215133983cce7a6c0b93ea8df36aa69.png

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/notification-reminder) 
> ### [Contact the user via email](mailto://lauradiaz1938@gmail.com) 

*Issue created by [**lauradiaz1938**](https://juiced.canny.io/admin/user/lauradiaz1938)  at 2021-12-07T18:25:53.161Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/notification-reminder) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
The red pulse button is at the bottom of the buttons it's looking like this coz the button is in active state and you can't see the boundary's,
