### ISSUE TITLE
Video tutorial germany 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#134]
### Hey,
I am from germany... But i would not be able to watch any video tutorials since all of the captions are in English. Please fix this so i can watch videos with german captions once their out.
https://canny.io/images/f4ec17189cab8ee5a3216cd3d789027c.png

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/video-tutorial-germany) 
> ### [Contact the user via email](mailto://dassnieder@juicedio.com) 

*Issue created by [**Das Snieader**](https://juiced.canny.io/admin/user/das-snieader)  at 2021-12-08T15:24:59.996Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/video-tutorial-germany) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
Currently the translation fo item is turned off during testing phase. In Live version you will be able to get proper translations.
