### ISSUE TITLE
Cost does not work 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#136]
### Cost does not work and does not show up on the listings table

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/cost-does-not-work) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/cost-does-not-work) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
![image](https://user-images.githubusercontent.com/24357511/145539715-32774317-0412-41f2-b40d-5b3416b1fad2.png)

Added a item in shopify with COG it appeared in the listing table correctly. Need more info
