### ISSUE TITLE
Ebay duplicate doesnt work 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#142]
### 

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/ebay-duplicate-doesnt-work) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/ebay-duplicate-doesnt-work) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
Note*

![image](https://user-images.githubusercontent.com/24357511/145537570-e5db3ebd-44d7-4ddf-8b83-59ec97279988.png)

Ebay duplicate is allowed only on few items. Don't consider them as bug if error is "Listing violates the Duplicate Listing policy.".
.
