### ISSUE TITLE
Bad alignment 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#143]
### The alignment of balance is incorrect. Please fix it so the space between balance and orders is the same as space between to anayltics and stat bubbles.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/bad-alignment) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/bad-alignment) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
I had to make small charts a little bigger to fit the balance with the same space 

How it looks now with the fix
![image](https://user-images.githubusercontent.com/48473628/146350697-bd289048-2465-4b82-a319-638414940eec.png)

vs how was it before

![image](https://user-images.githubusercontent.com/48473628/146350863-4d11acda-1170-4073-a732-b06a704f5738.png)
