### ISSUE TITLE
Cancel pop up too big 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#144]
### The cancel pop up is too big and should be the same size as the other smaller pop ups.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/cancel-pop-up-too-big) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/cancel-pop-up-too-big) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
@JuicedBen The cancel pop up has more inputs based on the platform selected 
ex.
This is when only shopify is seleted
![image](https://user-images.githubusercontent.com/48473628/146348790-0b8e8e03-c36d-4672-9c84-239f4c223bdc.png)
And this is when all the three platform as selected
![image](https://user-images.githubusercontent.com/48473628/146349372-fe54e52b-79c2-4400-ba58-447dac2cd7dc.png)

So we need more space for this
and also it's the same size as all the popup in orders are 
ex. Here is fullfil for shopify
![image](https://user-images.githubusercontent.com/48473628/146349563-f714a314-7ce5-46e6-bcaa-e07bf811478e.png)

I think it's ok, what do you think?
