### ISSUE TITLE
White pages 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#155]
### When you click add product or something before its loaded, it will whitepage. Often if you edit a input field after typing on it or you click the X in a search field, it whitepages.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/white-pages) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/white-pages) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
#152 related
