### ISSUE TITLE
Why is there 3 ups worldwide expedited 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#162]
### Why is there 3 ups worldwide expedited https://cdn.discordapp.com/attachments/778188273939251221/921901369777061888/unknown.png
> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/why-is-there-3-ups-worldwide-expedited) 
> ### [Contact the user via email](mailto://suraj@devss.io)

_Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z._

- - -
### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/why-is-there-3-ups-worldwide-expedited) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

┆Issue is synchronized with this [Jira Bug](https://juiced.atlassian.net/browse/JUICED-145) by [Unito](https://www.unito.io)

**Comment by iamsr** [comment]
@JuicedBen  they are not samejust their title is same in real they are (US,HK,CHINA) need more discussion with you regarding this like how we show this in frontend.
