### ISSUE TITLE
Enter your own api 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#166]
### https://cdn.discordapp.com/attachments/778188273939251221/921904981030895647/unknown.png The option to Enter your own is missing

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/enter-your-own-api) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/enter-your-own-api) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
![image](https://user-images.githubusercontent.com/48473628/150203465-903f7707-4cca-4a63-8c62-22b6aded3056.png)

The UI for this will be similar to this, earlier this to add something custom if it's allowed user's just have to enter the value now to make it more clear I have added this UI
