### ISSUE TITLE
Websites bugging 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#172]
### Messages and badges are bugging on websites. 1) Messages from discord are not being relayed 2) There are still often ghost badges

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/websites-bugging) 
> ### [Contact the user via email](mailto://suraj@devss.io) 

*Issue created by [**Suraj**](https://juiced.canny.io/admin/user/suraj-254)  at 2021-11-15T16:45:26.673Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/websites-bugging) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
Data that has been relayed after 20 DEC 2021 is going to be shown in the app.
