### ISSUE TITLE
Amazon search still sucks 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#181]
### I searched "Xbox 1s" and it gave me a video game and a printer. Fix this.
> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/amazon-search-still-sucks) 
> ### [Contact the user via email](mailto://admin@juicedio.com)

_Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-1358)  at 2020-12-07T14:13:38.470Z._

- - -
### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/amazon-search-still-sucks) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

┆Issue is synchronized with this [Jira Bug](https://juiced.atlassian.net/browse/JUICED-156) by [Unito](https://www.unito.io)

**Comment by iamsr** [comment]
![image](https://user-images.githubusercontent.com/24357511/150742383-4c6bca16-c8d4-4947-9a85-5462055215ca.png)

![image](https://user-images.githubusercontent.com/24357511/150742404-7374b038-edd5-47cf-ac88-f23f56638a72.png)


it's same as amazon
