### ISSUE TITLE
Shopify update Track quantity broken. 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#263]
### When trying to update the track quantity from "Yes" to "No" it DOESNT actually update. It just goes straight back to Yes. This is a major issue.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/shopify-update-track-quantity-broken) 
> ### [Contact the user via email](mailto://admin@juicedio.com) 

*Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-1358)  at 2020-12-07T14:13:38.470Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/shopify-update-track-quantity-broken) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

PLEASE NOTE THIS ISSUE IS UNCATEGORISED AND THE LABELS PRESENT HAVE DEFAULTED TO ALL LABELS. IF THIS ISSUE DOES NOT RELATE TO YOUR LABEL, PLEASE REMOVE YOUR LABEL.

**Comment by iamsr** [comment]
fixed
