### ISSUE TITLE
Amazon saudi connection doesnt work 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#264]
### When you try to connect saudi on amazon, this happens: https://cdn.discordapp.com/attachments/778188273939251221/959870685788909578/unknown.png

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/amazon-saudi-connection-doesnt-work) 
> ### [Contact the user via email](mailto://admin@juicedio.com) 

*Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-1358)  at 2020-12-07T14:13:38.470Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/amazon-saudi-connection-doesnt-work) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
Fixed
