### ISSUE TITLE
Shopify connection issues 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#265]
### When you try to connect your shopif yaccount (NOT THE REGULAR ONE) it does not work (see screenshot below).
To test, please connect the shopify store; juicedioltd (password is; Bentgate08) and as you can see you get this error;
https://canny.io/images/14baa20bcfdf4f409d934280eb16c012.png

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/shopify-connection-issues) 
> ### [Contact the user via email](mailto://admin@juicedio.com) 

*Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-1358)  at 2020-12-07T14:13:38.470Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/shopify-connection-issues) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
Shopify App won't install in real shopify account until it's published and approved by shopify you have to use development store meanwhile to test things in it.
