### ISSUE TITLE
Big size Profile Image

### ISSUE THREAD

**Issue by tecxar-neel** [juicedio/Bug-reports#28]
Sometimes if the profiel picture you try to upload is too big, it wont let you add it HOWEVER there is no error telling the user about this.

**Comment by iamsr** [comment]
Already Fixed.

**Comment by tecxar-neel** [comment]
{"message":"Request failed with status code 413","name":"Error","stack":"createError@http://localhost:8081/index.bundle?,}

I received this message when I upload big size image, can you please change the message

**Comment by iamsr** [comment]
seems like a frontend related error or a error when server was down...as the latest checked api response is like this 

![image](https://user-images.githubusercontent.com/24357511/144217241-956b3df5-0a6c-49a9-9a38-ea79f23ce8f3.png)

**Comment by tecxar-neel** [comment]
I checked and when I upload JPEG image I upload successfully but when I try with .png,.jpg then it shows the error

**Comment by iamsr** [comment]
I double checked with all the file format you told and everything is working fine. The error you posted in the comment is related to react-native (localhost:8081 bundle) please double check things on your end before posting something as bug for api. Thanks

For reference : https://github.com/facebook/react-native/issues/10404

**Comment by tecxar-neel** [comment]
@iamsr This isn't on the mobile end, seems like the server is rejecting large payload. 


We receive 413 error, which is send over from the server and not from client. 

This is web reference. 
The HTTP 413 Payload Too Large response status code indicates that the request entity is larger than limits defined by server.

If there is a file size limit, please mention it here so we can add those checks. 

Also please mention where is the application hosted?

**Comment by tecxar-neel** [comment]
ImageLink :- https://www.google.com/url?sa=i&url=https%3A%2F%2Fin.pinterest.com%2Fpin%2F636626097300077435%2F&psig=AOvVaw21DUYqKQdOklUMd5Rx1OPo&ust=1638617755115000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMDFsPzEx_QCFQAAAAAdAAAAABAq


<img width="1667" alt="Screenshot 2021-12-03 at 5 03 42 PM" src="https://user-images.githubusercontent.com/79091196/144596462-cf8b7894-fe97-4263-8eb9-241e8f0cc559.png">
<img width="2048" alt="Screenshot 2021-12-03 at 5 07 21 PM" src="https://user-images.githubusercontent.com/79091196/144596472-e1084fb3-f56d-4c18-bc6a-7b57521194f5.png">

**Comment by iamsr** [comment]
File Size Max - 2 MB
File Format  Support - jpeg, jpg, png, svg

**Comment by iamsr** [comment]
![image](https://user-images.githubusercontent.com/24357511/144604697-513b1d24-9e62-4e02-894f-7533f7c4d0e9.png)

Tested with 2.9 MB PNG Image.
