### ISSUE TITLE
Dark mode icon of categories

### ISSUE THREAD

**Issue by tecxar-neel** [juicedio/Bug-reports#29]
When on dark mode, the category icons are black and cannot be seen properl

SS:
![Simulator Screen Shot - iPhone 11 - 2021-11-29 at 20 11 58](https://user-images.githubusercontent.com/79091196/143991488-897dc8ab-3c3d-49b3-a282-65e4120192fb.png)
 -

**Comment by iamsr** [comment]
if possible you can use any filter library over it to convert the svg images to white in dark modes. 
https://github.com/iyegoroff/react-native-color-matrix-image-filters#supported-filters
Let me know if above thing works for your usecase

**Comment by tecxar-neel** [comment]
Thank you
