### ISSUE TITLE
Inputs not showing 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#47]
### Please go to https://juiced-admin.devss.io/dashboard/info and click "Add drops". This will allow you to send an item into hot items. When doing so, make sure you add all the inputs including images, links, titles, etc. Then test if all inputs you put showed up on the app. Last time I checked not all inputs are showing.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/inputs-not-showing) 
> ### [Contact the user via email](mailto://admin@juicedio.com) 

*Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-1358)  at 2020-12-07T14:13:38.470Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/inputs-not-showing) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by tecxar-neel** [comment]
This is done by me yesterday,
