### ISSUE TITLE
Reminders does not work 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#51]
### Reminders does not work

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/reminders-does-not-work) 
> ### [Contact the user via email](mailto://admin@juicedio.com) 

*Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-1358)  at 2020-12-07T14:13:38.470Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/reminders-does-not-work) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
![image](https://user-images.githubusercontent.com/48473628/144700204-b5cc1403-943e-4eaf-8dcd-40eb905b9c78.png)

@JuicedBen  do you mean this? 
The items here are urgent and discounts but as we discussed on meet you want it changed to the channels with reminders from discord. Did we plan on doing that?

**Comment by iamsr** [comment]
this a new change and will be done on later on stage with new feature list.
