### ISSUE TITLE
Shopify wrong text splash page

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#54]
### On the splash page, Shopify has "eBay is a great place to sell fashion, collectibles, electronics, tickets and more. Being one of the most popular marketplaces, you should be listing almost all of your inventory on this website." when it should say "Shopify is for resellers who want to build a clientele. Using Instagram, Facebook and other platforms, you can sell products directly to your followers with your very own Shopify website."

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/de-melde-einen-technischen-fehler/p/shopify-wrong-text-splash-page) 
> ### [Contact the user via email](mailto://ben@juicedio.com) 
**WARNING: This user speaks German. Please either avoid communication or contact them in German. You should use Google translate before sending emails or comments.**

*Issue created by [**Ben**](https://juiced.canny.io/admin/user/ben-2347)  at 2021-08-06T00:00:03.551Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/de-melde-einen-technischen-fehler/p/shopify-wrong-text-splash-page) and update the status to; "in progress". This feature request currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by ssnxd** [comment]
@JuicedBen  Fixed the issues
