### ISSUE TITLE
Cant delete without sku 

### ISSUE THREAD

**Issue by JuicedBen** [juicedio/Bug-reports#99]
### I cant delete listing without SKU? That is total bullshit. Please fix. And if you cant fix then make sure all listing have sku.

> ### [Reply to user on canny.io](https://juiced.canny.io/admin/board/report-a-bug/p/cant-delete-without-sku) 
> ### [Contact the user via email](mailto://danielsmith@juicedio.com) 

*Issue created by [**Daniel Smith**](https://juiced.canny.io/admin/user/daniel-smith-304)  at 2021-12-06T12:45:06.266Z.*

-------------------------------------------------------------------------------------------------------------------------------------

### Once you begin working on this bug, please go [the post](https://juiced.canny.io/admin/board/report-a-bug/p/cant-delete-without-sku) and update the status to; "in progress". This bug report currently has 1 votes and 0 comments. Please fix this within 5 hours, with 24 hours being the latest wait.

**Comment by iamsr** [comment]
not all item can have SKU which are added outside of our platform. Ebay Delete listing Api requires SKU to be present in listing if not it won't delete that data. Items which are added from our platform have SKU as required fields already.
